name: Order Service CI

on:
  push:
    paths:
      - "order-service/**"
  pull_request:
    paths:
      - "order-service/**"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: orderservice
          POSTGRES_USER: erkan
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Tests
        run: |
          cd order-service
          mvn test

      - name: Test Report
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: Order Service Tests
          path: order-service/target/surefire-reports/*.xml
          reporter: java-junit
